version: '3.8'

services:
  oracledb:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: esg-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s

  app:
    build: .
    container_name: esg-app
    ports:
      - "8080:8080"
    depends_on:
      oracledb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracledb:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  oracle_data: