name: CI/CD Pipeline for ESG Application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test
  deploy_staging:
    name: Deploy to Staging
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t esg-app:${{ github.sha }} .
      - name: Deploy to Staging
        run: |
          echo "Deploying version ${{ github.sha }} to staging"
          # docker-compose -f docker-compose.staging.yml up -d
  deploy_production:
    name: Deploy to Production
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t esg-app:${{ github.sha }} .
      - name: Deploy to Production
        run: |
          echo "Deploying version ${{ github.sha }} to production"
          # docker-compose -f docker-compose.prod.yml up -d
